channels:
- conda-forge
dependencies:
- python=3.7.13
- pip
- pip:
  - mlflow
  - cloudpickle==1.3.0
  - graphviz==0.10.1
  - lightgbm==2.2.3
  - matplotlib==3.2.2
  - pandas==1.3.5
  - pathlib==1.0.1
  - psutil==5.4.8
  - scikit-learn==1.0.2
name: mlflow-env
